### ISSUE TITLE
java.lang.InstantiationError: org.kairosdb.core.DataPoint

### ISSUE THREAD

**Issue by FrEaKmAn** [hugocore/kairosdb-rabbitmq#1]
First of all, thank you for this great plugin. I'm trying to make it work, but no luck. I'm running KairosDB 0.9.4-6.20140730155353 and I'm trying to insert the following data.

``` python
import pika

connection = pika.BlockingConnection(pika.ConnectionParameters('192.168.0.105'))
channel = connection.channel()
channel.basic_publish(exchange='', 
              routing_key='queue1', 
              body='{"tags":[{"name":"AI1"}], "value": "10", "timestamp": "1388530800000"}', 
              properties=pika.BasicProperties(
                content_type = 'application/json'
                      ))

connection.close()
```

but I get this error in logs...

```
06-17|20:09:59.955 [main] INFO  [Main.java:380] - Starting service class org.kairosdb.plugin.rabbitmq.core.RabbitmqService
06-17|20:09:59.955 [main] INFO  [null:-1] - [KRMQ] Starting to RabbitMQ consumer thread.
06-17|20:09:59.982 [main] INFO  [Main.java:266] - ------------------------------------------
06-17|20:10:00.013 [main] INFO  [Main.java:267] -      KairosDB service started
06-17|20:10:00.014 [main] INFO  [Main.java:268] - ------------------------------------------
06-17|20:10:00.103 [Thread-16] INFO  [null:-1] - [KRMQ] Connecting to RabbitMQ broker.
06-17|20:10:00.104 [Thread-16] INFO  [null:-1] - [KRMQ] Reading binding configuration from 'conf/bindings.json'.
06-17|20:10:00.140 [Thread-16] INFO  [null:-1] - [KRMQ] Waiting for messages of exchange 'exch1' to queue 'queue1' with bindingkey '#'.
06-17|20:10:00.152 [Thread-16] INFO  [null:-1] - [KRMQ] Waiting for messages of exchange 'exch2' to queue 'queue2' with bindingkey 'color.#'.
06-17|20:10:00.156 [Thread-16] INFO  [null:-1] - [KRMQ] Waiting for messages of exchange 'exch2' to queue 'queue3' with bindingkey 'size.#'.
Exception in thread "Thread-16" java.lang.InstantiationError: org.kairosdb.core.DataPoint
        at org.kairosdb.plugin.rabbitmq.core.RabbitmqConsumer.consumeMessage(Unknown Source)
        at org.kairosdb.plugin.rabbitmq.core.RabbitmqConsumer.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by hugocore** [comment]
Hum.. Weird. It seems that it is not able to instantiate an org.kairosdb.core.DataPoint object.

I checked KairosDB's source and nothing seems to be changed.

Let's try to debug it:
- Try to publish with "10.0" instead of "10". See if that works.
- Try using a previous version of KairosDB
- You can also try to check the source by importing this project to eclipse, go to src/main/java/org/kairosdb/plugin/rabbitmq/core/RabbitmqConsumer.java#consumeMessage debug it there, build and deploy it to your kairosdb's plugin folder

**Comment by FrEaKmAn** [comment]
Hi @hugocore 
1. 10.0 does not make any difference
2. I have downloaded the source, updated kairosdb.jar (which version is it?) to latest version (0.9.4-5) and upgraded commong-lang3. I compiled it and replaced kairosdb-rabbitmq.jar in lib folder. Now everything works.

Could you please check again on your end? And please update dependencies to include latest libs?

**Comment by hugocore** [comment]
Good to know. If you are deploying kairosdb-rabbitmq.jar into your kairosdb folder its version it's up to you. For development purposes I've updated to 0.9.4-5 to avoid this issue.
